name: flutter_socket_log_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  protobuf: ^2.0.1
  rxdart: ^0.27.3
  equatable: ^2.0.3
  flutter_screenutil: ^5.0.0+2
  flutter_scale_tap: ^1.0.5
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  shared_preferences: ^2.0.8
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

